[package]
name = "templates"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
tera = "1"
base64 = "0.11"
lazy_static = "1"
pulldown-cmark = "0.6"
toml = "0.5"
csv = "1"
image = "0.22"
regex = "1"
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
url = "2"

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library" }
config = { path = "../config" }
imageproc = { path = "../imageproc" }

[dev-dependencies]
mockito = "0.22"
